version: '3.8'
services:
  discord-bypass:
    build: .
    container_name: discord-bypass
    stdin_open: true   # Разрешаем интерактивный ввод
    tty: true          # Эмулируем TTY
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "11080:1080"