version: '3.8'

services:
  dpi-bypass:
    build: .
    container_name: discord-bypass
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - "11080:1080"  # Только SOCKS прокси
    # Убрал порт 53 полностью